name: Générer la Documentation Paaxio

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v4

      - name: Installer Doxygen et Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Générer la documentation
        run: doxygen Doxyfile

      - name: Configurer le domaine personnalisé
        run: echo "docs.paaxio.com" > docs/html/CNAME

      - name: Publier sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          force_orphan: true
